######################################################################
# Automatically generated by qmake (1.07a) Tue May 17 18:23:43 2011
######################################################################

TEMPLATE = app
INCLUDEPATH += .

SOURCES +=\
    main-viewer.cpp \
    main.cpp

HEADERS  += \
    viewer.h \
    Point.h \
    Cellule.h \
    Conteneur.h \
    ParserBoucle.h \
    Parser.h \
    ComplexeCubique.h

LIBS += -lglut -lqglviewer-qt4
