######################################################################
# Automatically generated by qmake (1.07a) Tue May 17 18:23:43 2011
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += BoucleParser.h \
           Cellule.h \
           ComplexeCubique.h \
           Conteneur.h \
           Parser.h \
           ParserBoucle.h \
           Point.h \
           viewer.h
SOURCES += main-viewer.cpp main.cpp
